#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: InterMedNet
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  International Network For Medical Education
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  A comprehensive international platform that encourages the exchange of knowledge and fosters lifelong learning for doctors from all corners of the world.
#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: admin@intermednet.org
org_street_address: Ombersley road #Please include suite number on the line below
org_address_suite: 6
org_city: Cardiff
org_state: Wales
org_zip:  NP2 03EE # Enter zip on next line. Be sure to indent by two spaces.

org_phone: false # Enter phone on next line. Be sure to indent by two spaces.
  

#SOCIAL MEDIA
org_twitter_username: intermednet
org_facebook_username: intermednet
org_instagram_username:

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name: false
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
is_501c3: false

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: false
tinyletter_username: false

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: true

#COLOR SCHEME
#Select one of the five color schemes (default, one, two, three, or four)
color_scheme: three

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: false
smartergiving_id: false
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
